# write_init.cmake
# Called at build time by softsim_install_to_pkg.
# Variables passed in via -D:
#   DEST_FILE  — full path to __init__.py
#   MODULE     — extension target name, e.g. _engine

if(NOT EXISTS "${DEST_FILE}")
    string(REGEX REPLACE "^_" "" _clean "${MODULE}")
    file(WRITE "${DEST_FILE}"
"# Auto-generated by CMake — do not edit.
# Re-exports everything from the compiled C++ extension.
from .${MODULE} import *  # noqa: F401, F403
from .${MODULE} import __doc__  # noqa: F401
")
    message(STATUS "Generated ${DEST_FILE}")
else()
    message(STATUS "Skipping ${DEST_FILE} (already exists — edit freely)")
endif()
